version: '3.12'

services:
  backend:
    image: gcr.io/bigdata-project1-450016/backend:latest
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/bigdata-project1-450016-c5fdbfb5391a.json
    volumes:
      - ./secrets/bigdata-project1-450016-c5fdbfb5391a.json:/secrets/bigdata-project1-450016-c5fdbfb5391a.json:ro
    entrypoint: ["/bin/sh", "-c", 
      "gcloud auth activate-service-account --key-file=/secrets/bigdata-project1-450016-c5fdbfb5391a.json && 
      gcloud secrets versions access latest --secret=API_KEYS --project=bigdata-project1-450016 > /app/backend/endpoints.env && 
        exec uvicorn main:app --host 0.0.0.0 --port 8000"]
    depends_on:
      - redis
  # 其他服务保持不变
  frontend:
    image: gcr.io/bigdata-project1-450016/frontend:latest
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

volumes:
  redis_data:
